import { GetStaticProps } from 'next';
import Head from 'next/head';

export default function Home({about}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="px-8 pt-8 ">
          <h5 className="py-2 font-mono text-base text-color1" >{about.name}</h5>
          <h1 className="py-2 text-6xl font-bold text-color3" >{about.title1}</h1>
          <h1 className="text-6xl font-bold text-color2" >{about.title2}</h1>
        </div>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const about = await fetch('http://localhost:3000/api/about').then((res) => res.json());
  
  return {
    props: {
      about,
    }
  };
}